name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: [stable, beta, nightly]
        features: ["", "--no-default-features"]

    steps:
    - name: Checkout sources
      uses: actions/checkout@v6
    - name: Install toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.toolchain }}
        override: true
        components: clippy
    - name: Build
      run: cargo build --verbose ${{ matrix.features }}
    - name: Run tests
      run: cargo test --verbose ${{ matrix.features }}
    - name: Verify lints
      run: cargo clippy -- -D warnings
