name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: [stable, beta, nightly]
        features: ["", "--no-default-features"]

    steps:
    - uses: actions/checkout@v6
    - name: Set Toolchain
      run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
    - name: Build
      run: cargo build --verbose ${{ matrix.features }}
    - name: Run tests
      run: cargo test --verbose ${{ matrix.features }}
